services:
  - docker

before_install:
  - docker build -t box-consulting/react-test -f ./web_client/Dockerfile.dev ./web_client

scripts:
  - docker run -e CI=true box-consulting/react-test npm test

after_success:
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
  - docker build -t box-consulting/ttwa-web-client ./worker
  - docker push box-consulting/ttwa-web-client

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "box-consulting-web-client"
  env: "KubernetesTraining-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-003903245551"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
