sudo: required

services:
  - docker

before_install:
  - docker build -t dtrodger/react-test -f ./web_client/Dockerfile.dev ./web_client

scripts:
  - docker run -e CI=true dtrodger/react-test npm test

after_success:
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
  - docker build -t dtrodger/ttwa-web-client ./web_client
  - docker build -t dtrodger/ttwa-web-server ./web_server
  - docker build -t dtrodger/ttwa-proxy ./proxy
  - docker build -t dtrodger/ttwa-worker ./worker
  - docker push dtrodger/ttwa-web-client
  - docker push dtrodger/ttwa-web-server
  - docker push dtrodger/ttwa-proxy
  - docker push dtrodger/ttwa-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "kubernetes-training"
  env: "KubernetesTraining-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-003903245551"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
